### ISSUE TITLE
Crear Issues !!!

### ISSUE THREAD

**Issue by Markkos89** [Markkos89/enRuta#5]
@IsaacMiguel  @leandrodapello @fjassi 

Bueno pensé en algo que quería compartir con ustedes. Es sobre todo esto acerca de github. El tema es que como dije hoy yo soy programador (y de pedo), no soy project manager, coordinador, etc.. Y creo que tampoco lo son ustedes. Entonces bueno pensé, voy a hacer mi mejor esfuerzo y hacerlo como lo haria un programador, y encontre todo esto de github, que estuvieron el mismo dilema, y se podria decir que la empresa no contrata project managers. En fin, la idea es que volquemos todas las ideas que queramos en "issues", creando un issues, y volcando la idea ahí. Entonces me pregunte, cómo volcamos una idea? Bueno, basicamente el titulo deberia ser lo mas descriptivo posible sin alcanzar la categoria de "muy largo". El contenido deberia explicar qué hay que hacer, de qué consta, como se podría hacer, cómo se debería hacer, con qué se lo podria hacer, de qué requiere, quien lo podria hacer, quien hizo algo parecido, cuanto se tardaria en hacer.

Si se ponen a pensar todas estas preguntas ya explican mucho más de una simple idea, ya brindaria muchísima mas informacion que, por ejemplo, "hay que hacer el alta de usuarios", podria ser "hay que hacer el abm de usuarios", con mas info como, "incluye la vista, controlador y modelo", "requiere que primero se haga la base de datos o minimo la tabla usuarios", etc. Bueno esto es solo una idea que se me ocurrio compartir con ustedes para que ninguno sea el único que tenga que escribir issues, o tareas a hacer, ademas a veces es más fácil ver desde afuera a otro porque uno se va imaginando las tareas nomas y despues otro será el que la haga. Cuando empecemos a decir "ah, yo lo puedo hacer eso" ahi es cuando nos asignamos la tarea y listo, uno es responsable de hacerla, a su tiempo y a su forma. Y si no es el caso que podamos ver las tareas del otro, anotemos nuestras propias tareas, o ideas, o sugerencias a nosotros mismos o a otro, y despues otro contestando en ese mismo issue se va engrosando la idea. Tenemos la ventaja que somos pocos, y estamos enfocados en lo mismo que es hacer la app. Si se arma una cadena despues se pueden rescatar cosas y pasar todo en limpio y pasa a un Milestone como les habia dicho y eso significa que ya esta considerado. Desde links a lo que sea, osea, pedazos de codigo, todo lo que se les ocurra, vuelquenlo acá, como yo voy a hacer.

# Resumiendo:

### - Qué hay que hacer?
 
CREAR ISSUES

### - De qué consta? 

crear todos los issues que se puedan como tareas a hacer

### - Como se podría hacer? 

blabla

### - Cómo se debería hacer? 
con la mayor descripcion posible, saber las tecnologias que se usarian o la capa donde se programaria o datos o "ifs" resueltos o "fors" jaja, todo lo que sea mas orientado al desarrollo seria muy util. Por ej si se es sobre una vista hasta se puede recomendar hasta cierta clase de css de bootstrap, como poner a todos los controles como "form-control", etc.. si es una tabla poner el tipo de campo o limite de caracteres, etc, TODO SUMA, y esta es la parte donde mas se escribe creo.
### - Con qué se lo podria hacer? 
github jaja
### - De qué requiere? 
sentarse y escribir
### - Quien lo podria hacer? 
todos
### - Quien hizo algo parecido? 
blabla
### - Cuanto se tardaria en hacer? 
blabla

de hecho, este mismo issue lo podemos usar como ejemplo para mejorarlo, por ejemplo, poniendo mas items a la lista de arriba, qué otra cosa se les ocurriria? Es buena idea porque puedo armar un template, usando el código que esta arriba en la parte de edicion y usarlo como template de preguntas para cada issue que abramos... algo así:

``# Nombre del issue``
``### - Qué hay que hacer?``
``### - De qué consta?``
``### - Como se podría hacer?``
``### - Cómo se debería hacer?``
``### - Con qué se lo podria hacer?``
``### - De qué requiere?``
``### - Quien lo podria hacer?``
``### - Quien hizo algo parecido?``
``### - Cuanto se tardaria en hacer?``

una manera de llamar la atencion de alguien es tagearlo con @, por ej: ``@Markkos89 mira esto" y a mi me llega una notificacion, tambien cada vez que uno comente en este issue, o pase algo, tambien se puede configurar para que te envie un mail.

podemos subir imagenes, es facil y rapido con paint y guardarlo o hacer un doc de word y subirlo acá o tambien armar todo con el editor de github, si quieren les puedo escribir mas o menos como se usa, es medio raro, se llama "markdown" y es distinto.

Me parece que mientras más cosas volquemos acá va a ser mejor para todos, y recuerden que este proyecto esta OCULTO, lo puse como PRIVADO. Nadie sin nuestro permiso lo puede ver.

Si quieren puedo explicar como es para subir código a github. Hasta documentos word podemos subir, no solo el código que necesitamos para correr el sistema. Tambien se pueden subir documentos y se van pusheando y actualizando lo que tienen dentro, como un archivo html o js...

Si lo utilizamos bien y le sacamos el jugo puede ser muy provechoso!

**Comment by IsaacMiguel** [comment]
Copiado! Ahora me mando uno que es con el tema de mongo y ver si se entiende y esta bien.

**Comment by Markkos89** [comment]
muy bueno migue!
